import React,{useEffect,useRef,useState} from 'react';
import HarbourMap,{PEOPLE,PLACES,PROPS,Figure,ObjectArt,personName} from './HarbourMap.jsx';
import {createHarbourWorld,advanceHarbourWindow,finishPlayerIntervention,availableCash,placePublicOrder,phoneContact} from './harbourSpine.js';
import {performPlayerAction,visibleActions,visitLocation,PLAYER_COUNTERPARTIES} from './playerGame.js';
import {diagnosePlayer} from './playerDiagnosis.js';
import {ACTION_COPY,TARGET_ACTIONS,actionLine,reaction,readableResult,friendlyBlock} from './harbourPresentation.js';
import {ECONOMIC_GOODS as GOODS} from './economicContent.js';
import {selectDialogue,visibleNames} from './dialogueContent.js';
import {NEWSPAPER_OVERRIDES,UI_COPY,SCAR_COPY,itemLabel} from './presentationCopy.js';
import {AUDIO_CUES} from './worldLifeContent.js';
import './harbour.css';
import SpokenLine from './SpokenLine.jsx';
const SAVE='sunflower-harbour-map-v1';
function initial(){try{const s=JSON.parse(localStorage.getItem(SAVE));if(s?.version===1&&s.world?.production)return s.world}catch{}return createHarbourWorld()}
function useSound(){const audio=useRef(null),[enabled,setEnabled]=useState(false);function sound(kind='paper'){if(!enabled)return;const ctx=audio.current||(audio.current=new AudioContext());ctx.resume();const o=ctx.createOscillator(),g=ctx.createGain();o.type=kind==='water'?'sine':'triangle';o.frequency.setValueAtTime(kind==='coin'?680:kind==='phone'?180:kind==='water'?90:280,ctx.currentTime);o.frequency.exponentialRampToValueAtTime(kind==='water'?55:140,ctx.currentTime+.2);g.gain.setValueAtTime(.0001,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.035,ctx.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+.3);o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+.32)}useEffect(()=>{if(!enabled)return;const timer=setInterval(()=>sound('water'),6500);return()=>clearInterval(timer)},[enabled]);return {sound,enabled,toggle:()=>setEnabled(x=>!x)}}
function Comic({scene,onClose,children}){const dialog=useRef(null);const [shown,setShown]=useState(1),[paused,setPaused]=useState(false);useEffect(()=>{setShown(1);setPaused(false);dialog.current?.querySelector('button')?.focus()},[scene.title]);useEffect(()=>{if(paused||shown>=scene.lines.length)return;const t=setTimeout(()=>setShown(n=>n+1),2400);return()=>clearTimeout(t)},[shown,paused,scene]);return <section ref={dialog} className="comic" role="dialog" aria-modal="true" aria-label={scene.title}><button className="close" aria-label="Close comic" onClick={onClose}>×</button><h2>{scene.title}</h2><div className="comic-panels" onWheel={()=>{setPaused(true);setShown(scene.lines.length)}} onTouchMove={()=>{setPaused(true);setShown(scene.lines.length)}}>{scene.lines.slice(0,shown).map((line,i)=><article className={`comic-panel panel-${i}`} key={i}><svg viewBox={i===1?"70 40 120 100":"35 10 155 140"} aria-hidden="true"><svg width="220" height="150" viewBox={`${(PLACES[scene.location]||PLACES.viewing_room)[0]-150} ${(PLACES[scene.location]||PLACES.viewing_room)[1]-90} 300 200`}><image href="/art/harbour-working.png" width="1400" height="900" preserveAspectRatio="none"/></svg>{(scene.person||scene.people?.length>0)&&<g transform={`translate(${65+i*15} 122) scale(1.2)`}><Figure scale={.43} id={scene.people?.[i%scene.people.length]||scene.person||'aspen'} pose={i%2?'working':'neutral'}/></g>}<g transform="translate(120 65)"><ObjectArt kind={scene.object||'paper'}/></g></svg><p>{line}</p></article>)}</div>{shown<scene.lines.length&&<button className="response" onClick={()=>setShown(scene.lines.length)}>Read at my pace</button>}{shown===scene.lines.length&&<div className="responses">{children||<button className="response" onClick={onClose}>Back to the harbour</button>}</div>}</section>}
function Ending({world,onReturn}){const d=diagnosePlayer(world);const names={valuation:'Judging a price',execution:'Getting things done',commitments:'Keeping promises',liquidityCredit:'Keeping money free',information:'Listening and looking',verificationAdaptation:'Checking and changing your mind',positioningStress:'Deciding under pressure',marketStructure:'Finding someone to trade with'};return <section className="ending" role="dialog" aria-label="Your story"><h1>You have the sunflower.</h1><p>The water still moves. Someone is counting glasses.</p><h2>Your time here</h2><p>{d.outcome.startingCash} tins when you arrived. {d.outcome.endingCash} now.</p><p>{d.outcome.fulfilled} promises kept. {d.outcome.breached} missed.</p><h2>What your choices suggest</h2>{d.radar.filter(x=>x.score!==null).map(x=><p key={x.key}>{names[x.key]}: {x.score>=65?'often shaped your choices':x.score<45?'sometimes cost you':'still taking shape'}.</p>)}{d.evidenceCount<3&&<p>There is too little here to call it a pattern.</p>}<h2>What stayed with you</h2>{d.scars.length?d.scars.map(s=><p key={s.name}><strong>{SCAR_COPY[s.name]?.[0]||'An encounter that stayed'}</strong><br/>{SCAR_COPY[s.name]?.[1]||'Your choices left a mark on this visit.'}</p>):<p>No single encounter has left a defining mark yet.</p>}<button className="response" onClick={onReturn}>Keep looking at the harbour</button></section>}
export default function AppCore(){
 const [world,setWorld]=useState(initial),[focus,setFocus]=useState(null),[drawer,setDrawer]=useState(null),[message,setMessage]=useState(''),[pending,setPending]=useState(null),[page,setPage]=useState(0),[comic,setComic]=useState(null),[bag,setBag]=useState(null),[contact,setContact]=useState(null),[archive,setArchive]=useState(false),[readDay,setReadDay]=useState(-1),[hint,setHint]=useState(()=>!localStorage.getItem(SAVE)),[price,setPrice]=useState(6),[tradeItem,setTradeItem]=useState('Fresh Mackerel');
 const [readText,setReadText]=useState(null),[restOffer,setRestOffer]=useState(false);
 const {sound,enabled,toggle}=useSound(),pg=world.playerGame,p=world.actors.player;
 useEffect(()=>{try{localStorage.setItem(SAVE,JSON.stringify({version:1,world}))}catch{setMessage('Your browser could not save this visit. Keep this page open.')}},[world]);
 useEffect(()=>{const key=e=>{if(comic||pg.home||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(e.key==='Escape'){setDrawer(null);setComic(null);setFocus(null);setBag(null)}if(e.key==='n')setDrawer(d=>d==='notes'?null:'notes');if(e.key==='p')setDrawer(d=>d==='phone'?null:'phone');if(e.key==='g')setDrawer(d=>d==='news'?null:'news')};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[comic,pg.home]);
 const scoped=focus?{...world,playerGame:{...pg,location:focus.location}}:world;
 const required=PLAYER_COUNTERPARTIES;
 const personPresent=!focus||!PEOPLE[focus.id]||world.actors[focus.id]?.location===focus.location;
 let actions=focus&&personPresent?visibleActions(scoped).filter(a=>(TARGET_ACTIONS[focus.id]||[]).includes(a.id)&&!a.disabled&&(!required[a.id]||world.actors[required[a.id]].location===focus.location)&&actionLine(a,world)):[];
 if(focus?.id==='crate')actions=actions.filter(a=>a.id!=='lime_represent'||!pg.lime.representation).filter(a=>a.id!=='lime_inspect'||!pg.lime.inspected).filter(a=>a.id!=='lime_deliver'||pg.lime.representation).filter(a=>a.id!=='lime_represent'||pg.lime.inspected||a.payload.mode!=='disclose');
 actions=actions.filter(a=>!world.production.playerActions.some(x=>x.id===a.id&&x.day===world.day));
 const known=focus&&p.contacts.includes(focus.id),isPerson=focus&&PEOPLE[focus.id],pageSize=isPerson?2:3,selectedActions=actions.slice(page*pageSize,page*pageSize+pageSize);
 function select(f){setReadText(null);setRestOffer(false);sound(AUDIO_CUES[f.location]?.[0]||'paper');setFocus(f);setDrawer(null);setPage(0);setPending(null);setMessage('');setHint(false);if(f.id==='orders'){setDrawer('trade');setBag(null)}}
 function blocked(reason){if(/attention|intervention/.test(reason)){setRestOffer(true);setFocus(null);setDrawer(null);setPending(null);setMessage('')}else setMessage(friendlyBlock(reason));}
 function arrive(w,loc){const n=visitLocation(w,loc);if(n.playerGame.location!==loc){blocked(n.playerGame.lastBlock||'attention');return null}return n}
 function choose(a){if(a.id==='trade_bridge'&&world.production.tradeStock.length){setPending(a);setMessage(`Sell this bundle for ${world.day%4===0?1:4} tins. It leaves your bag when the buyer pays.`);return}if(a.id==='joel_invitation'){setPending(a);setMessage(`Supper is on day ${world.day+4}. Bring the special catch: it costs 10 tins and arrives on day ${world.day+3}. It must still be fresh when you bring it.`);return}if(['lime_accept','invest_nursery','finance_receivable','speculate_lot','private_proxy','auction_finance','auction_bid','trade_bridge','misstate_public_listing','assemble_onewheel'].includes(a.id)){setPending(a);setMessage(ACTION_COPY[a.id][1]+(a.id==='auction_finance'?` Repay on day ${pg.routes.yasmin.auctionDay+5}; the promised object is ${p.inventory.find(u=>!u.pledgedTo)?.kind||'not available'}.`:''));return}execute(a)}
 function execute(a){setPending(null);if(!personPresent){setMessage('They have moved away. Look for them on the map.');return}let before=arrive(world,focus?.location||pg.location);if(!before)return;const after=performPlayerAction(before,a.id,a.payload);if(after.playerGame.lastBlock){blocked(after.playerGame.lastBlock);return}if(JSON.stringify(after)===JSON.stringify(before)){setMessage('Nothing changed. The person or object is not ready for that today.');return}const advanced=finishPlayerIntervention(world,after,[focus?.id,required[a.id],...(a.id==='invite_toad_circle'?after.production.toadChat.members:a.id==='sonya_attend'?['joel']:[])].filter(Boolean));setWorld(advanced);sound('coin');const result=a.id==='talk_here'?selectDialogue(after,a.payload.actor).text:readableResult(before,after,a);setMessage(result+(advanced.day>world.day?' The light changes. A new day begins.':''));setPage(0);
 if(['lime_inspect','sonya_attend','auction_bid','cliff_commit','invite_toad_circle'].includes(a.id)){setComic({location:focus?.location,title:{lime_inspect:'The short crate',sonya_attend:'Borrowed chairs',auction_bid:'The raised hand',cliff_commit:'Above the water',invite_toad_circle:'A little circle'}[a.id],people:a.id==='invite_toad_circle'?after.production.toadChat.members.filter(id=>id!=='player'):a.id==='sonya_attend'?['joel','sonya']:[],person:a.id==='sonya_attend'?'joel':a.id==='auction_bid'?'yasmin':a.id==='cliff_commit'?null:'aspen',object:a.id==='lime_inspect'?'Lime':a.id==='cliff_commit'?'Sunflower':a.id==='invite_toad_circle'?'toad':'paper',lines:a.id==='lime_inspect'?['The string comes loose.','Twenty limes. Three bruised.','“That is the whole crate?” The paper says twenty-four.']:a.id==='invite_toad_circle'?['The jar rests between the pots.',result,'For a while, nobody offers a price.']:a.id==='sonya_attend'?['A chair is pulled to the table.',result,'Someone passes the plate. Nobody counts the helpings.']:a.id==='cliff_commit'?['A wheel mark ends at the path.',result,'Below, the boats still move.']:['A hand goes up.',result,'The bowl stays on the cloth until the sale closes.'],choices:a.id==='lime_inspect'});}
 }
 function introduce(){const before=arrive(world,focus.location);if(!before)return;const after=performPlayerAction(before,'meet',{actor:focus.id});if(after.playerGame.lastBlock){blocked(after.playerGame.lastBlock);return}setWorld(finishPlayerIntervention(world,after,[focus.id]));setMessage(`“${PEOPLE[focus.id].name}.” You exchange names and a number. “Leave a message if I’m out.”`);sound('paper')}
 function nextDay(){setRestOffer(false);const next=advanceHarbourWindow(world);setWorld(next);setPage(0);setPending(null);setFocus(null);setDrawer(null);setBag(null);sound('water');const fills=next.market.tape.filter(t=>t.day===next.day&&(t.buyerId==='player'||t.sellerId==='player'));setMessage(fills.length?fills.map(t=>`${t.buyerId==='player'?'Bought':'Sold'} ${t.quantity} ${t.item} for ${t.price*t.quantity} tins.`).join(' '):next.weather!==world.weather?(next.weather==='storm'?'Rain on the water. The cliff stones are wet.':'The rain has cleared.'): 'A new day. Boats and people have moved.');if(!pg.sunflower.owned&&next.playerGame.sunflower.owned)setComic({title:'A sunflower',person:'yasmin',object:'Sunflower',lines:['The sale is over.','The bowl changes hands. A sunflower comes with it.','You hold it. Nothing supernatural happens.']});}
 function order(side){const before=arrive(world,'public_clearing');if(!before)return;const n=placePublicOrder(before,'player',side,tradeItem,Number(price));if(n.market.orders.length===before.market.orders.length){blocked(n.playerGame.lastBlock||'The clerk cannot take that offer. Check the price, free tins and whether the object is already promised.');return}const settled=finishPlayerIntervention(world,n);setWorld(settled);const fill=settled.market.tape.slice(world.market.tape.length).find(t=>t.buyerId==='player'||t.sellerId==='player');setMessage(fill?`${fill.buyerId==='player'?'Bought':'Sold'} ${fill.quantity} ${itemLabel(fill.item)} for ${fill.price*fill.quantity} tins. ${fill.buyerId==='player'?'It is in your bag.':'It has left your bag.'}`:side==='sell'?`One ${tradeItem} is set aside. If someone pays ${price} tins, it changes hands as the harbour moves. Otherwise it stays yours.`:`${price} tins are set aside. If a seller accepts, you receive one ${tradeItem} as the harbour moves. Otherwise you keep your money.`);sound('paper')}
 const claims=world.claims.filter(c=>c.holderId==='player'||c.issuerId==='player'),inventory=p.inventory;
 const title=focus?(isPerson?personName(world,focus.id):{crate:'The crate',cargo:'The cargo',bowl:'The bowl',plants:'The plants',paper:'The paper',orders:'The posted offers'}[focus.id]||'A closer look'):'';
 function edge(which){sound('paper');setDrawer(d=>d===which?null:which);if(which==='news')setReadDay(world.day);setFocus(null);setPending(null);setMessage('')}
 const localActions=Object.fromEntries(Object.keys(PLACES).map(location=>[location,visibleActions({...world,playerGame:{...pg,location}}).filter(a=>!a.disabled&&(!required[a.id]||world.actors[required[a.id]].location===location))]));
 const activeProps=new Set(PROPS.filter(([id,loc])=>id==='orders'||localActions[loc]?.some(a=>(TARGET_ACTIONS[id]||[]).includes(a.id))).map(([id])=>id));
 const dialogueText=message||(!personPresent?'They have moved away.':isPerson?selectDialogue(world,focus.id).text:reaction(world,focus?.id));
 const hasChoices=Boolean(pending||personPresent&&(!message||world.attention.used<world.attention.budget)&&(actions.length||isPerson));
 const guide=pg.sunflower.owned?'You have the sunflower. Your pocket book holds the story of this visit.':pg.lime.stage==='held'?'Open the crate before promising what is inside.':pg.routes.sonya.stage==='invited'?`Keep the fresh catch for supper on day ${pg.routes.sonya.supperDay+1}.`:pg.routes.juan.stage==='planning'?'The wheel parts come with the cargo; your pocket book keeps the list.':pg.routes.juan.built?'Take the wheel to the path after it has stood overnight.':p.contacts.length?'Ask someone about the harbour, or offer something from your bag at the exchange.':'You are looking for a sunflower; someone in the harbour may know a way.';
 return <main className="harbour-game"><div className="world-layer" inert={comic||pg.home?'':undefined}>
 <HarbourMap world={world} selected={focus} onFocus={select} activeProps={activeProps}/>
 <header className="pocket-top"><button onClick={()=>edge('notes')} aria-label="Open money and notes">Sunflower <span>⌄</span></button><span>Day {world.day+1}</span><button onClick={nextDay} aria-label="Next day">☀ <small>Next day</small></button><button onClick={toggle} aria-label={enabled?'Mute sound':'Enable sound'}>{enabled?'♪':'♩'}</button></header>
 <aside className="edge-objects"><button onClick={()=>edge('news')} aria-label="Open newspaper" className={readDay<world.day?'unread':''}>▤<span>Paper</span></button><button onClick={()=>edge('phone')} aria-label="Open phone">▯<span>Phone</span></button></aside>
 {hint&&<p className="gesture-hint" onClick={()=>setHint(false)}>Drag to move · scroll or pinch to look closer<br/><small>Touch a person or an object.</small></p>}
 {message&&!focus&&!drawer&&<div className="world-reaction" role="status">{message}<button className="close" aria-label="Dismiss notice" onClick={()=>setMessage('')}>×</button></div>}
 {focus&&!comic&&drawer!=='trade'&&<section className="conversation" aria-label="Conversation"><button className="close" aria-label="Close conversation" onClick={()=>setFocus(null)}>×</button><strong>{title}</strong><SpokenLine key={dialogueText} text={dialogueText} hasChoices={hasChoices} onReady={()=>setReadText(dialogueText)} onDone={()=>{setFocus(null);setMessage('')}}/>

 {readText===dialogueText&&(pending?<div className="responses"><button className="response" onClick={()=>execute(pending)}>Yes, on those terms.</button><button className="response" onClick={()=>{setPending(null);setMessage('')}}>Let me think.</button></div>:isPerson&&!known?<div className="responses"><button className="response" onClick={introduce}>Hello. Can we keep in touch?</button></div>:<div className="responses">{isPerson&&known&&personPresent&&<button className="response" onClick={()=>execute({id:'talk_here',payload:{actor:focus.id}})}>Stay a moment.</button>}{selectedActions.slice(0,isPerson?2:3).map((a,i)=><button className="response" key={a.id+JSON.stringify(a.payload)} onClick={()=>choose(a)}>{actionLine(a,world)}</button>)}{actions.length>pageSize&&<button className="response secondary" onClick={()=>setPage(n=>(n+1)*pageSize>=actions.length?0:n+1)}>Something else…</button>}{!actions.length&&<p className="quiet">{isPerson?'You can stay a moment, or leave them to it.':'You can leave it here for now.'}</p>}</div>)}
 </section>}
 {drawer&&<section className={`pocket-drawer drawer-${drawer}`} aria-label={drawer==='notes'?'Money and notes':drawer==='news'?'Newspaper':drawer==='phone'?'Phone':drawer==='restart'?'Start a new visit':'Trading'}><button className="close" aria-label="Close drawer" onClick={()=>setDrawer(null)}>×</button>
 {drawer==='news'&&<><h2>The Harbour Paper</h2><small>Day {world.day+1}</small>{world.newspaper.slice(archive?-8:-3).reverse().map(n=><article key={n.id}><h3>{NEWSPAPER_OVERRIDES[n.id]?.headline||visibleNames(world,n.headline)}</h3><p>{NEWSPAPER_OVERRIDES[n.id]?.report||visibleNames(world,n.report)}</p></article>)}<button className="response" onClick={()=>setArchive(x=>!x)}>{archive?'Fold the old pages away':'A few earlier pages'}</button></>}
 {drawer==='phone'&&<><h2>{UI_COPY.phone}</h2>{!p.contacts.length&&<p>No numbers yet. Say hello to someone in the harbour.</p>}{p.contacts.filter(id=>PEOPLE[id]).map(id=><button className="contact-line" key={id} onClick={()=>setContact(id)}>{PEOPLE[id].name}</button>)}{contact&&p.contacts.includes(contact)&&<article><h3>{PEOPLE[contact].name}</h3>{world.messages.filter(m=>m.to===contact||m.from===contact).slice(-4).map(m=><p key={m.id}>{m.from==='player'?'You: ':''}{m.text}</p>)}<button className="response" onClick={()=>{setWorld(phoneContact(world,contact,'Can we talk when you are free?'));setMessage('Message sent.');sound('phone')}}>Can we talk when you are free?</button></article>}{world.production.toadChat&&<article><h3>The little circle</h3><p>🐸 🌒 ?</p><p>A jar. A few people. An unfinished conversation.</p></article>}</>}
 {drawer==='notes'&&<><h2>{UI_COPY.pocketBook}</h2><p><strong>{availableCash(world,'player')} tins</strong> free to spend. A tin is money here.</p>{p.cash!==availableCash(world,'player')&&<p>{p.cash-availableCash(world,'player')} tins already promised.</p>}<p>{world.production.marketStanding.status==='SUSPENDED'?'The clerk will not take your offers. Correct your papers at the exchange, or speak to someone who arranges private sales.':world.production.marketStanding.strikes?'The clerk is checking your papers more closely.':'The clerk accepts your papers.'}</p><h3>Promises</h3>{pg.commitments.filter(c=>c.status==='open').map(c=><p key={c.id}>{c.id==='lime-delivery'?'Return the lime crate':c.id==='grandma-supper'?'Bring the special catch to supper':c.id==='auction-bid'?'Wait for the bowl sale':'Repay the borrowed tins'} · Day {c.dueDay+1}</p>)}{!pg.commitments.some(c=>c.status==='open')&&<p>Nothing due.</p>}{claims.map(c=><p key={c.id}>{c.issuerId==='player'?'You owe':'Owed to you'} {c.face} tins · Day {c.dueDay+1} · {c.status==='open'?'waiting':c.status==='settled'?'paid':'unpaid'}</p>)}<h3>Prices you have seen</h3>{world.market.tape.slice().reverse().map(t=><p key={t.id}>Day {t.day+1} · {t.quantity} {t.item} · {t.price} tins each</p>)}{!world.market.tape.length&&<p>No completed sales seen yet.</p>}{['planning','ready'].includes(pg.routes.juan.stage)&&<><h3>Up the path</h3><p>Bring a steel rim, chain link, brake cable and handlebar tape from the cargo to the parcel bench. Assembly costs 3 tins. Let it stand overnight; wait for a dry path.</p></>}<h3>Your exchanges</h3>{world.production.playerActions.filter(a=>a.counterparty).slice().reverse().map((a,i)=><p key={i}>Day {a.day+1} · {personName(world,a.counterparty)||'At the counter'} · paid {a.cost}, received {a.revenue} tins</p>)}{pg.sunflower.owned&&<button className="response" onClick={()=>setWorld(performPlayerAction(world,'finish_run'))}>Look back on this visit</button>}<button className="response secondary" onClick={()=>setDrawer('restart')}>Start a new visit…</button></>}
 {drawer==='restart'&&<><h2>Start again?</h2><p>This replaces the saved visit in this browser.</p><button className="response" onClick={()=>{setWorld(createHarbourWorld());setDrawer(null);setFocus(null);setContact(null);setMessage('');setHint(true)}}>Yes, a new visit</button><button className="response" onClick={()=>setDrawer('notes')}>Keep this visit</button></>}
 {drawer==='trade'&&<><h2>The exchange counter</h2><p>“Tell me what you want, and your price. I’ll match it when a buyer and seller agree. I keep the promised money or object aside until then.”</p><label>One object<select value={tradeItem} onChange={e=>setTradeItem(e.target.value)}>{Object.entries(GOODS).filter(([k,v])=>v.mode==='PUBLIC_MARKET'&&(inventory.some(u=>u.kind===k)||world.market.orders.some(o=>o.status==='open'&&o.item===k))).map(([k])=><option key={k}>{k}</option>)}</select></label><label>Tins for one<input type="number" min="1" step="1" value={price} onChange={e=>setPrice(e.target.value)}/></label><div className="responses"><button className="response" onClick={()=>order('buy')}>I’ll pay {price} for one.</button>{inventory.some(u=>u.kind===tradeItem&&!u.pledgedTo)&&<button className="response" onClick={()=>order('sell')}>Sell mine for {price}.</button>}</div><h3>Papers on the counter</h3>{world.market.orders.filter(o=>o.status==='open'&&o.item===tradeItem).slice(0,5).map(o=><p key={o.id}>{o.side==='buy'?'Someone offers':'Someone asks'} {o.price} tins · {o.quantity} {o.item}</p>)}{pending?<div><p>{ACTION_COPY[pending.id]?.[1]}</p><button className="response" onClick={()=>execute(pending)}>Yes, on those terms.</button><button className="response" onClick={()=>setPending(null)}>Let me think.</button></div>:actions.filter(a=>['restitution','fire_sale','misstate_public_listing'].includes(a.id)).map(a=><button className="response" key={a.id} onClick={()=>choose(a)}>{actionLine(a,world)}</button>)}</>}
 {message&&<p role="status" className="receipt">{message}</p>}
 </section>}
 {!focus&&!drawer&&!comic&&!restOffer&&<p className="harbour-guide">{guide}</p>}
 {restOffer&&<section className="conversation" role="dialog" aria-label="Tomorrow"><p>There is not enough time left for that today.</p><button className="response" onClick={nextDay}>Start tomorrow.</button><button className="response" onClick={()=>setRestOffer(false)}>Keep looking around.</button></section>}
 <footer className="inventory-ribbon" aria-label="Your objects">{inventory.map(u=><button key={u.unitId} aria-label={`Your ${itemLabel(u.kind)}`} className={bag===u.unitId?'selected':''} onClick={()=>{setBag(bag===u.unitId?null:u.unitId);setMessage('');sound()}}><ObjectArt kind={u.kind}/><span>{itemLabel(u.kind)}</span>{u.pledgedTo&&<i aria-label="Promised as security">⌁</i>}</button>)}{world.production.tradeStock.length>0&&<button onClick={()=>{select({id:'packing',location:'joels_bar'});setMessage('This bundle is yours. Ask at the bar whether they need packing paper.')}}><ObjectArt kind="parcel"/><span>Packing bundle</span></button>}{world.production.toads.filter(t=>t.status==='held').map(t=><button key={t.id} onClick={()=>select({id:'plants',location:'nursery'})}><ObjectArt kind="toad"/><span>Little jar</span></button>)}{pg.sunflower.owned&&<button aria-label="Your sunflower" onClick={()=>setWorld(performPlayerAction(world,'finish_run'))}><ObjectArt kind="Sunflower"/><span>Sunflower</span></button>}{!inventory.length&&!pg.sunflower.owned&&!world.production.tradeStock.length&&!world.production.toads.some(t=>t.status==='held')&&<p>Your bag is empty.</p>}</footer>
 {bag&&inventory.some(u=>u.unitId===bag)&&<section className="object-slip"><button className="close" aria-label="Close object" onClick={()=>setBag(null)}>×</button><h3>{itemLabel(inventory.find(u=>u.unitId===bag).kind)}</h3><p>{inventory.find(u=>u.unitId===bag).pledgedTo?'Promised against a loan. Repay before offering it elsewhere.':'Yours to carry. A sale needs someone who will pay.'}</p>{GOODS[inventory.find(u=>u.unitId===bag).kind]?.mode==='PUBLIC_MARKET'&&<button className="response" onClick={()=>{setTradeItem(inventory.find(u=>u.unitId===bag).kind);setDrawer('trade');setFocus({id:'orders',location:'public_clearing'});setBag(null)}}>Offer it at the exchange</button>}{inventory.find(u=>u.unitId===bag).kind==='Exceptional Invitation Fish'&&<button className="response" onClick={()=>{select({id:'table',location:'sonyas_kitchen'});setBag(null)}}>Bring the fresh catch to supper</button>}{inventory.find(u=>u.unitId===bag).kind==='Built Onewheel'&&<button className="response" onClick={()=>{select({id:'path',location:'cliff_path'});setBag(null)}}>Take the wheel to the path</button>}{inventory.find(u=>u.unitId===bag).kind==='Orgeat'&&<button className="response" onClick={()=>{select({id:'bottle',location:'joels_bar'});setBag(null)}}>Bring the bottle to the bar</button>}</section>}
 </div>{comic&&<Comic scene={comic} onClose={()=>setComic(null)}>{comic.choices&&['disclose','ambiguous','misrepresent'].map(mode=><button className="response" key={mode} onClick={()=>{execute({id:'lime_represent',payload:{mode}});setComic(null)}}>{actionLine({id:'lime_represent',payload:{mode}},world)}</button>)}</Comic>}
 {pg.home&&<Ending world={world} onReturn={()=>setWorld({...world,playerGame:{...pg,home:false}})}/>}
 </main>
}
