// Living Economy architecture decision: one state-transition authority owns actor
// balances, unit-level goods, claims, knowledge, commitments and the institutional
// order book. A deterministic priority/utility agenda was chosen over a state
// machine (too brittle) and GOAP (unnecessary search). Background sectors persist
// with finite cash and renewable-but-paid production capacity. Spot orders reserve
// cash or unit IDs; services, living assets and claims remain separate ontologies.
// Event-driven variable-cost capacity is the default; equal and heterogeneous
// schedulers remain injectable for causal comparison.
import { ECONOMIC_GOODS as GOODS, LIVING_ASSET_FAMILIES, CLAIM_TYPES, SERVICE_TYPES, contentGraph } from "./economicContent.js";
import { advanceLivingSystems, consumeCompostInput, initializeLivingSystems, recordSpoilage } from "./livingSystems.js";
import { initializePlayerGame, resolvePlayerDay, settlePlayerDebts } from "./playerGame.js";
import { advanceHarbourBeat, advanceRelationalHarbour, initializeRelationalHarbour, prepareRelationalDay, relationalDiagnostics, sceneSnapshot } from "./relationalHarbour.js";
import { advanceProductionGame, initializeProductionGame, productionDiagnostics } from "./productionGame.js";

// Seeded world variation; actors still react to the resulting facts with the same rules.
function harbourChance(seed,day,kind){let h=(seed^Math.imul(day+1,2654435761))>>>0;for(const c of kind)h=Math.imul(h^c.charCodeAt(0),16777619)>>>0;h^=h>>>16;return (h>>>0)/4294967296;}
const cp=x=>structuredClone(x); const unit=(w,kind,owner,source="initial")=>({unitId:`u${++w.nextUnit}`,kind,owner,age:0,costBasis:GOODS[kind]?.value||0,source,opened:false,remaining:GOODS[kind]?.servings||1});
const ACTOR_IDS=["player","joel","aspen","wong","juan","yasmin","dima"];
const LOC={player:"harbour_berth",joel:"joels_bar",aspen:"harbour_berth",wong:"parcel_counter",juan:"nursery",yasmin:"viewing_room",dima:"back_room"};
export const SPINE_CONFIG={attentionPerDay:4,orderLifetime:3,scheduler:"variable",backgroundRegeneration:.55,visitorRate:.45};
const actor=(id,cash,capacity)=>({id,cash,location:LOC[id],capacity,busy:0,inventory:[],knowledge:[],contacts:[],commitments:[],relationships:{},reliability:{payment:3,delivery:3,representation:3},actions:[],income:0,costs:0});
const bg=(id,cash,capacity)=>({...actor(id,cash,capacity),background:true,productionBudget:24,consumptionBudget:24});
function add(w,id,names,source="initial"){for(const name of names)w.actors[id].inventory.push(unit(w,name,id,source));}
const ev=(w,type,data={})=>{const row={id:`ev${++w.nextEvent}`,day:w.day,type,...data};w.evidence.push(row);return row};
const playerEv=(w,type,data={})=>{const row=ev(w,type,{source:'public_clearing',location:'public_clearing',confidence:1,weight:1,...data});if(w.playerGame&&!w.playerGame.notebook.includes(row.id))w.playerGame.notebook.push(row.id);return row};
const flow=(w,direction,sector,actorId,reason,amount,returnClass)=>{w.externalFlows.push({day:w.day,direction,sector,actorId,reason,amount,returnClass});};
export function createHarbourWorld(seed=41,config={}){
 const w={version:2,seed,day:0,nextUnit:0,nextEvent:0,config:{...SPINE_CONFIG,...config},weather:"fair",actors:{player:actor("player",18,4),joel:actor("joel",34,6),aspen:actor("aspen",30,7),wong:actor("wong",18,5),juan:actor("juan",12,5),yasmin:actor("yasmin",58,4),dima:actor("dima",20,4),households:bg("households",80,8),crews:bg("crews",54,7),small_boats:bg("small_boats",20,6),wharf_suppliers:bg("wharf_suppliers",35,6),visitors:bg("visitors",0,4)},attention:{budget:4,used:0},worldTruth:[{id:"truth-shoal",kind:"route",value:"shoal obstruction",privateTo:["aspen"]}],publicFacts:[],newspaper:[],opportunities:[],evidence:[],messages:[],claims:[],livingAssets:[],services:[],market:{orders:[],reservations:[],tape:[],settlementFloat:0},externalFlows:[],returnLedger:[],stats:{barCycles:0,barCustomers:0,barFailures:0,aspenDepartures:0,aspenReturns:0,wongJobs:0,juanHarvests:0,yasminLoans:0,dimaServices:0,backgroundDemandSatisfied:0,reservationConflicts:0,infoChangedDecisions:0},bar:{capacity:5,servings:{},last:null,spoilage:0},aspenRoute:{status:"preparing",deadline:3,cargoCapacity:4,cargo:[],departureDay:null,cost:0},wongBusiness:{capacity:3,stored:[],operatingCost:1},yasminBook:{lockedCapital:0},dimaBook:{guarantees:[]}};
 add(w,"player",["Fresh Mackerel","Lime"]);add(w,"joel",["Rum","Lime","Pineapple","Mint","Soda","Ice","Orgeat","Orange Curaçao"]);add(w,"aspen",["Hardtack Tin","Reusable Crate","Brass Compass"]);add(w,"wong",["Packing Paper","Reusable Crate","Rope Offcut","Glass Bottle"]);add(w,"small_boats",["Fresh Mackerel","Fresh Mackerel","Smoked Eel","Sea Lettuce"]);add(w,"wharf_suppliers",["Lime","Salted Cod","Hardtack Tin","Soda","Ice","Presta Inner Tube","Chain Quick-Link","Packing Paper"]);
 for(const [species,x] of Object.entries(LIVING_ASSET_FAMILIES).slice(0,4))w.livingAssets.push({id:`plant-${species}`,ownerId:"juan",species,stage:x.stages[1],health:1,maturity:0,inputDue:1,pledgedTo:null});
 w.claims.push({id:"juan-working-capital",type:"future_output_claim",issuerId:"juan",holderId:null,face:8,dueDay:10,collateralAssetId:"plant-lime_tree",status:"seeking_finance"});
 initializeLivingSystems(w); initializePlayerGame(w); initializeRelationalHarbour(w); initializeProductionGame(w);
 for(const id of ['small_boats','wharf_suppliers'])for(const item of new Set(w.actors[id].inventory.filter(u=>GOODS[u.kind]?.mode==='PUBLIC_MARKET').map(u=>u.kind)))placePublicOrderMutable(w,id,'sell',item,GOODS[item].value);
 publish(w,"news-opening","Parcel counter opens","Wong is accepting short custody and handoff work.",null,"social"); rebuildOpportunities(w);return w;
}
const reservations=(w,actorId,kind)=>w.market.reservations.filter(r=>r.actorId===actorId&&r.kind===kind);
export const availableCash=(w,id)=>w.actors[id].cash-reservations(w,id,"cash").reduce((s,r)=>s+r.amount,0)-(id==="player"?w.playerGame?.commitments.filter(c=>c.status==="open").reduce((s,c)=>s+(c.lockedCash||0),0)||0:0);
export const availableInventory=(w,id)=>{const ids=new Set(w.market.reservations.filter(r=>r.kind==="unit").map(r=>r.unitId));return w.actors[id].inventory.filter(x=>!ids.has(x.unitId)&&!x.pledgedTo);};
function reserve(w,o){if(o.side==="buy"){const amount=o.price*o.quantity;if(availableCash(w,o.actorId)<amount){w.stats.reservationConflicts++;return false}w.market.reservations.push({orderId:o.id,actorId:o.actorId,kind:"cash",amount});}else{const xs=availableInventory(w,o.actorId).filter(x=>x.kind===o.item).slice(0,o.quantity);if(xs.length<o.quantity){w.stats.reservationConflicts++;return false}for(const x of xs)w.market.reservations.push({orderId:o.id,actorId:o.actorId,kind:"unit",unitId:x.unitId});o.unitIds=xs.map(x=>x.unitId)}return true}
function placePublicOrderMutable(w,actorId,side,kind,price,{attentionCost=actorId==="player"?1:0,quantity=1}={}){const a=w.actors[actorId];if(!a||GOODS[kind]?.mode!=="PUBLIC_MARKET"||!['buy','sell'].includes(side)||!Number.isFinite(price)||!Number.isInteger(quantity)||price<=0||quantity<1)return false;if(actorId==="player"){const standing=w.production?.marketStanding;if(standing?.status==='SUSPENDED'){w.playerGame.lastBlock='Octopus has suspended public listing access; restitution or a private venue remains available.';return false}if(standing?.listingLimit&&w.market.orders.filter(o=>o.actorId==='player'&&o.status==='open').length>=standing.listingLimit){w.playerGame.lastBlock=`Institutional restriction permits ${standing.listingLimit} open listing.`;return false}if(w.attention.used+attentionCost>w.attention.budget){w.playerGame.lastBlock='No intervention time remains today.';return false}}const o={id:`o${++w.nextEvent}`,actorId,side,item:kind,price,quantity,status:"open",created:w.day,expires:w.day+w.config.orderLifetime};if(!reserve(w,o))return false;w.market.orders.push(o);if(actorId==="player")w.attention.used+=attentionCost;ev(w,"order_committed",{actorId,side,item:kind,quantity,price});if(actorId==='player')playerEv(w,'public_order',{summary:`Placed a public ${side} order for ${quantity} ${kind} at ${price}🥫.`,goods:[kind],returnClass:'TRADE',process:{execution:.5,marketStructure:.7,valuation:.3},style:{publicPrivate:-1,takerProvider:side==='sell'?.8:-.5}});return true}
export function placePublicOrder(current,actorId,side,kind,price,options={}){const w=cp(current);placePublicOrderMutable(w,actorId,side,kind,price,options);return w}
function clear(w){expireOrders(w);const buys=w.market.orders.filter(o=>o.status==="open"&&o.side==="buy").sort((a,b)=>b.price-a.price||a.created-b.created);const sells=w.market.orders.filter(o=>o.status==="open"&&o.side==="sell").sort((a,b)=>a.price-b.price||a.created-b.created);for(const b of buys){for(const s of sells){if(b.status!=="open"||s.status!=="open"||b.item!==s.item||b.actorId===s.actorId||s.price>b.price)continue;const q=Math.min(b.quantity,s.quantity),price=s.price,buyer=w.actors[b.actorId],seller=w.actors[s.actorId];if(availableCash(w,b.actorId)+reservations(w,b.actorId,"cash").filter(r=>r.orderId===b.id).reduce((n,r)=>n+r.amount,0)<price*q)continue;const unitIds=(s.unitIds||[]).slice(0,q);if(unitIds.length!==q||!unitIds.every(id=>seller.inventory.some(x=>x.unitId===id)))continue;const moved=unitIds.map(id=>seller.inventory.splice(seller.inventory.findIndex(x=>x.unitId===id),1)[0]);w.market.settlementFloat+=price*q;buyer.cash-=price*q;seller.cash+=price*q;w.market.settlementFloat-=price*q;for(const x of moved){x.owner=buyer.id;buyer.inventory.push(x)}b.quantity-=q;s.quantity-=q;s.unitIds=(s.unitIds||[]).filter(id=>!unitIds.includes(id));w.market.reservations=w.market.reservations.filter(r=>!unitIds.includes(r.unitId));const cashReservation=w.market.reservations.find(r=>r.orderId===b.id&&r.kind==='cash');if(cashReservation)cashReservation.amount=b.quantity*b.price;if(!b.quantity)b.status="filled";if(!s.quantity)s.status="filled";w.market.tape.push({id:`t${w.market.tape.length+1}`,day:w.day,item:b.item,quantity:q,price,buyerId:b.actorId,sellerId:s.actorId,institution:"octopus_clearing"});w.returnLedger.push({day:w.day,class:"TRADE",actorId:seller.id,amount:price*q,context:"public_market"});ev(w,"trade_settled",{buyerId:b.actorId,sellerId:s.actorId,item:b.item,quantity:q,price});if(b.actorId==='player'||s.actorId==='player')playerEv(w,'market_fill',{summary:`Public order filled: ${q} ${b.item} at ${price}🥫.`,goods:[b.item],returnClass:'TRADE',weight:2,process:{execution:.8,marketStructure:1,valuation:.4},style:{publicPrivate:-1,takerProvider:s.actorId==='player'?.8:-.6}});if(buyer.background)w.stats.backgroundDemandSatisfied+=q;}}
 for(const o of w.market.orders)if(o.status==="open"&&o.expires<w.day)o.status="expired";const open=new Set(w.market.orders.filter(o=>o.status==="open").map(o=>o.id));w.market.reservations=w.market.reservations.filter(r=>open.has(r.orderId));}
function expireOrders(w){for(const order of w.market.orders)if(order.status==="open"&&order.side==="sell"&&!order.unitIds?.every(id=>w.actors[order.actorId].inventory.some(u=>u.unitId===id)))order.status="cancelled";for(const order of w.market.orders)if(order.status==="open"&&order.expires<w.day)order.status="expired";const open=new Set(w.market.orders.filter(order=>order.status==="open").map(order=>order.id));w.market.reservations=w.market.reservations.filter(reservation=>open.has(reservation.orderId));}
function publish(w,id,headline,report,truthId,category){if(w.newspaper.some(x=>x.id===id))return;const x={id,day:w.day,headline,report,truthId,category,public:true};w.newspaper.push(x);w.publicFacts.push(x);w.actors.player.knowledge.push(id);ev(w,"newspaper_published",{articleId:id})}
function notice(w){const relevant={aspen:["harbour","weather"],joel:["social","commercial"],wong:["social","commercial"],juan:["weather"],yasmin:["social","auction"],dima:["commercial"]};for(const [id,cats]of Object.entries(relevant))for(const f of w.publicFacts)if(cats.includes(f.category)&&!w.actors[id].knowledge.includes(f.id)){w.actors[id].knowledge.push(f.id);ev(w,"fact_noticed",{actorId:id,factId:f.id})}}
function score(a,c){return c.urgency*4+c.value-c.cost-c.risk+(a.relationships[c.actorId]||0)-a.busy*.3}
function choose(w,id,candidates){const a=w.actors[id];return candidates.filter(c=>!c.fact||a.knowledge.includes(c.fact)).sort((x,y)=>score(a,y)-score(a,x)||x.id.localeCompare(y.id))[0]}
function background(w){
 const demands={households:[['Fresh Mackerel',7],['Tomato',5],['Basil',4],['Packing Paper',3],['Soda',6]],crews:[['Salted Cod',10],['Lime',9],['Hardtack Tin',6],['Rope Offcut',5],['Ice',6]]};
 if(w.config.backgroundDemandScale!==0)for(const [id,rows] of Object.entries(demands)){const [k,p]=rows[w.day%rows.length];const stock=w.actors[id].inventory.filter(unit=>unit.kind===k).length;if(stock<2&&!w.market.orders.some(o=>o.status==='open'&&o.actorId===id&&o.side==='buy'&&o.item===k)&&availableCash(w,id)>=p)placePublicOrderMutable(w,id,'buy',k,p);}
 const production=[['small_boats','Fresh Mackerel',6,2],['small_boats','Sea Lettuce',5,4],['small_boats','Rope Offcut',3,5],['wharf_suppliers','Salted Cod',8,3],['wharf_suppliers','Lime',7,4],['wharf_suppliers','Packing Paper',2,3],['wharf_suppliers','Soda',5,5],['wharf_suppliers','Ice',4,2],['wharf_suppliers','Hardtack Tin',4,6]];
 if(w.config.backgroundSupplyScale!==0)for(const [id,k,p,every] of production){const a=w.actors[id];if(w.day%every===0&&a.productionBudget>0&&a.cash>=1){a.productionBudget--;a.cash--;a.costs++;a.inventory.push(unit(w,k,id,'bounded_production'));flow(w,'out','boat_and_wharf_inputs',id,'bounded_production_input',1,'OPERATE');ev(w,'background_production',{actorId:id,item:k,cost:1});}if(!w.market.orders.some(o=>o.status==='open'&&o.actorId===id&&o.side==='sell'&&o.item===k)&&availableInventory(w,id).some(x=>x.kind===k))placePublicOrderMutable(w,id,'sell',k,p);}
 if(w.day%4===0)for(const id of ['crews','households']){w.actors[id].cash+=5;flow(w,'in','outside_work',id,'bounded_labour_service',5,'OPERATE')}
 if(w.day%12===0)for(const id of ['small_boats','wharf_suppliers']){const a=w.actors[id];if(a.productionBudget<8&&a.cash>=4){a.cash-=4;a.productionBudget+=6;flow(w,'out','production_inputs',id,'renew_production_capacity',4,'OPERATE')}}
}
function openBarUnit(w,kind){const a=w.actors.joel,x=a.inventory.find(u=>u.kind===kind);if(!x)return false;a.inventory.splice(a.inventory.indexOf(x),1);w.bar.servings[kind]=(w.bar.servings[kind]||0)+(GOODS[kind].servings||1);return true}
function joel(w){const a=w.actors.joel;a.busy=3;for(const k of ['Rum','Lime','Ice'])if((w.bar.servings[k]||0)<2)openBarUnit(w,k);const locals=w.day%2?1:0,visitors=w.day%3===0?1:0,demand=locals+visitors,served=Math.min(demand,w.bar.capacity,w.bar.servings.Rum||0,w.bar.servings.Lime||0,w.bar.servings.Ice||0);const local=Math.min(locals,served),external=served-local;if(local&&availableCash(w,'households')>=local*6){w.actors.households.cash-=local*6;a.cash+=local*6}else if(local){w.stats.barFailures++}if(external){a.cash+=external*7;flow(w,'in','visiting_customers','joel','bar_service',external*7,'OPERATE')}for(const k of ['Rum','Lime','Ice'])w.bar.servings[k]=(w.bar.servings[k]||0)-served;w.stats.barCycles++;w.stats.barCustomers+=served;w.stats.barFailures+=demand-served;if(served)w.returnLedger.push({day:w.day,class:'OPERATE',actorId:'joel',amount:local*6+external*7,context:'bar_service'});w.bar.last={demand,served,localServed:local,externalServed:external,reason:served<demand?'input_or_cash':null};if((w.bar.servings.Rum||0)<2&&!w.market.orders.some(o=>o.status==='open'&&o.actorId==='joel'&&o.item==='Rum'))placePublicOrderMutable(w,'joel','buy','Rum',12);if((w.bar.servings.Lime||0)<2&&!w.market.orders.some(o=>o.status==='open'&&o.actorId==='joel'&&o.item==='Lime'))placePublicOrderMutable(w,'joel','buy','Lime',9);if(w.day%6===0&&availableCash(w,'joel')>=12){for(const k of ['Ice','Rum'])a.inventory.push(unit(w,k,'joel','bounded_wholesale'));a.cash-=12;a.costs+=12;flow(w,'out','bar_wholesale','joel','complete_service_bundle',12,'OPERATE');}}
function aspen(w){const a=w.actors.aspen,r=w.aspenRoute,graph=w.relationshipEcology?.routeGraph||{},selected=graph[r.selectedRoute]||{duration:3,cost:10,revenue:18,cargo:['Lime']};if(r.status==='preparing'){const disrupted=a.knowledge.includes('news-storm');const c=choose(w,'aspen',[{id:'depart',urgency:w.day>=r.deadline?4:1,value:selected.revenue,cost:selected.cost+(disrupted?8:0),risk:selected.risk+(disrupted?5:0),fact:disrupted?'news-storm':null},{id:'delay',urgency:2,value:disrupted?16:2,cost:2,risk:1}]);if(c.id==='delay'&&disrupted&&!r.disruptionHandled){r.deadline++;r.disruptionHandled=true;w.stats.infoChangedDecisions++;ev(w,'information_changed_plan',{actorId:'aspen',decision:'delay'});return}if(w.day>=r.deadline&&availableCash(w,'aspen')>=selected.cost){a.cash-=selected.cost;a.costs+=selected.cost;a.location='away';r.status='away';r.departureDay=w.day;r.activeRoute=r.selectedRoute||'medium';r.activeDuration=selected.duration;r.activeCargo=[...(r.cargoPlan||selected.cargo)].slice(0,r.cargoCapacity);w.stats.aspenDepartures++;flow(w,'out','route_services','aspen',`voyage_${r.activeRoute}_cost`,selected.cost,'OPERATE');}}else if(w.day-r.departureDay>=(r.activeDuration||3)){const route=graph[r.activeRoute]||selected;a.cash+=route.revenue;a.income+=route.revenue;a.location='harbour_berth';r.status='preparing';r.deadline=w.day+Math.max(3,route.duration);w.stats.aspenReturns++;flow(w,'in','outside_clients','aspen',`delivery_${r.activeRoute}_commission`,route.revenue,'OPERATE');for(const cargo of (r.activeCargo||route.cargo).filter(x=>GOODS[x])){a.inventory.push(unit(w,cargo,'aspen',`route_${r.activeRoute}_import`));if(GOODS[cargo].mode==='PUBLIC_MARKET')placePublicOrderMutable(w,'aspen','sell',cargo,GOODS[cargo].value+2)}w.returnLedger.push({day:w.day,class:'OPERATE',actorId:'aspen',amount:route.revenue-route.cost,context:`${r.activeRoute}_logistics_margin`});}}
function wong(w){const a=w.actors.wong;a.busy=2;if(w.day%4===0&&availableCash(w,'wong')>=1){a.cash--;a.costs++;flow(w,'out','counter_supplies','wong','parcel_operating_inputs',1,'OPERATE');}}
function juan(w){const a=w.actors.juan;a.busy=2;for(const p of w.livingAssets.filter(x=>x.ownerId==='juan')){p.maturity++;p.health=Math.max(.4,p.health-(w.weather==='storm'?.08:.02));const def=LIVING_ASSET_FAMILIES[p.species];if(p.maturity>=def.maturityDays){const k=def.outputs[0];a.inventory.push(unit(w,k,'juan','living_asset_yield'));p.maturity=0;w.stats.juanHarvests++;w.returnLedger.push({day:w.day,class:'INVEST',actorId:'juan',amount:GOODS[k].value,context:'crop_yield'});if(GOODS[k].mode==='PUBLIC_MARKET')placePublicOrderMutable(w,'juan','sell',k,GOODS[k].value);}}if(w.day%5===0&&a.cash>=2){const compost=consumeCompostInput(w);const cashCost=Math.max(0,2-compost);a.cash-=cashCost;a.costs+=cashCost;if(cashCost)flow(w,'out','growing_inputs','juan','plant_inputs',cashCost,'INVEST')}}
function yasmin(w){const a=w.actors.yasmin;a.busy=1;if(w.day%12===1&&!w.claims.some(c=>c.issuerId==='juan'&&['seeking_finance','open'].includes(c.status)))w.claims.push({id:`juan-output-${w.day}`,type:'future_output_claim',issuerId:'juan',holderId:null,face:8,dueDay:w.day+8,collateralAssetId:'plant-mint',status:'seeking_finance'});const candidate=w.claims.find(c=>c.status==='seeking_finance'&&!c.holderId);if(candidate&&availableCash(w,'yasmin')>=candidate.face*.7&&candidate.collateralAssetId){const advance=Math.floor(candidate.face*.7);a.cash-=advance;w.actors[candidate.issuerId].cash+=advance;candidate.holderId='yasmin';candidate.status='open';w.stats.yasminLoans++;w.yasminBook.lockedCapital+=advance;w.returnLedger.push({day:w.day,class:'FINANCE',actorId:'yasmin',amount:0,context:'secured_loan'});}for(const c of w.claims.filter(c=>c.holderId==='yasmin'&&c.issuerId!=='player'&&c.status==='open'&&c.dueDay<=w.day)){const issuer=w.actors[c.issuerId],pay=Math.min(c.face,Math.max(0,availableCash(w,c.issuerId)-4));issuer.cash-=pay;a.cash+=pay;c.status=pay===c.face?'settled':'default';w.yasminBook.lockedCapital=Math.max(0,w.yasminBook.lockedCapital-Math.floor(c.face*.7));w.returnLedger.push({day:w.day,class:'FINANCE',actorId:'yasmin',amount:pay,context:c.status});}if(w.day%15===0&&a.cash>=12){a.cash-=12;a.inventory.push(unit(w,'Gelatin Silver Print, 20 × 25 cm','yasmin','consignment_purchase'));flow(w,'out','private_estates','yasmin','provenance_asset_purchase',12,'SPECULATE');w.returnLedger.push({day:w.day,class:'SPECULATE',actorId:'yasmin',amount:-12,context:'provenance_position'});}}
function dima(w){const c=w.claims.find(x=>x.status==='default'&&!x.workout);if(c){const holder=w.actors[c.holderId];const fee=Math.min(2,Math.max(0,availableCash(w,c.holderId)));if(fee){holder.cash-=fee;w.actors.dima.cash+=fee;c.workout=true;c.dueDay+=3;w.stats.dimaServices++;w.returnLedger.push({day:w.day,class:'INTERMEDIATE',actorId:'dima',amount:fee,context:'workout'});}}}
function expirePerishables(w,elapsed=1){for(const a of Object.values(w.actors))for(let i=a.inventory.length-1;i>=0;i--){const x=a.inventory[i],life=GOODS[x.kind]?.shelfLife;if(life&&(x.age+=elapsed)>life){a.inventory.splice(i,1);recordSpoilage(w,x,a.id);ev(w,'spoilage',{actorId:a.id,item:x.kind,costBasis:x.costBasis});}}}
function rebuildOpportunities(w){w.opportunities=[];if(w.aspenRoute.status==='preparing')w.opportunities.push({id:'aspen-route',location:'harbour_berth',title:"Aspen's departure",status:'Cargo and route conditions remain live.',deadline:w.aspenRoute.deadline,attentionCost:1});if((w.bar.servings.Lime||0)<3)w.opportunities.push({id:'bar-input',location:'joels_bar',title:"Joel's Bar",status:'A service input is running low.',deadline:w.day+2,attentionCost:1});if(w.market.orders.some(o=>o.status==='open'))w.opportunities.push({id:'clearing',location:'public_clearing',title:'Public Clearing',status:'Open bids and asks await counterparties.',deadline:w.day+1,attentionCost:0});}
export function economicTerms(w,counterpartyId,{baseCredit=6,baseDeposit=.2,requiresInspection=false}={}){const a=w.actors[counterpartyId],r=a?.reliability||{payment:0,delivery:0,representation:0};return{creditLimit:r.payment>=3?baseCredit:0,depositRate:r.delivery>=3?baseDeposit:Math.min(1,baseDeposit+.3),inspectionRequired:requiresInspection||r.representation<3,relationshipDiscount:0};}
export function meetContact(current,id){const w=cp(current);if(!w.actors[id]||id==='player'||w.attention.used>=w.attention.budget)return w;w.attention.used++;if(!w.actors.player.contacts.includes(id))w.actors.player.contacts.push(id);ev(w,'contact_met',{actorId:id});return w}
export function phoneContact(current,id,text='Can we follow up?'){
 const w=cp(current),a=w.actors[id];if(!w.actors.player.contacts.includes(id)||!a)return w;
 const places={joels_bar:'at the bar',nursery:'among the plants',harbour_berth:'by the boats',parcel_counter:'at the parcel counter',viewing_room:'with the things for sale',back_room:'in the side room',old_hall:'at the screening',sonyas_kitchen:'at supper',cliff_path:'up the path'};
 const reply=a.location==='away'?'Still out on the water. I’ll be back when the crossing is done.':a.busy>=a.capacity?'I saw your message. My hands are full; try me tomorrow.':`I’m ${places[a.location]||'out for a moment'}. Come over if you want to talk.`;
 w.messages.push({id:`m${++w.nextEvent}`,day:w.day,from:'player',to:id,text,remote:true,physicalTransfer:false},{id:`m${++w.nextEvent}`,day:w.day,from:id,to:'player',text:reply,remote:true,physicalTransfer:false});
 ev(w,'phone_follow_up',{actorId:id});return w;
}

 export function advanceHarbourWindow(current){const w=cp(current);w.day++;w.attention.used=0;w.playerGame.location='harbour_berth';for(const [id,a] of Object.entries(w.actors)){a.busy=0;a.actions=[];if(LOC[id]&&!(id==='aspen'&&w.aspenRoute.status==='away'))a.location=LOC[id]}w.weather=harbourChance(w.seed,w.day,'weather')<.2?'storm':'fair';if(w.config.publishNews!==false&&w.day===1)publish(w,'news-storm','Shoal marker under repair','The harbour office expects delays near the eastern shoal.','truth-shoal','harbour');if(w.config.publishNews!==false&&w.day===2)publish(w,'news-screening','Free harbour screening','A restored comedy screens in the old hall.',null,'social');if(w.config.publishNews!==false&&w.day===3)publish(w,'news-framed','Crew reports calm passage','One crew reports calm water; the obstruction was not inspected.','truth-shoal','public_life');notice(w);prepareRelationalDay(w);background(w);if(w.config.clearingAvailable!==false)clear(w);else expireOrders(w);const jobs=[['joel',4,joel],['aspen',6,aspen],['wong',3,wong],['juan',3,juan],['yasmin',2,yasmin],['dima',2,dima]];for(const [id,cost,fn] of jobs){if(w.actors[id].removed||w.actors[id].capacity<=0)continue;const before=w.returnLedger.length+w.evidence.length;const cap=Math.max(0,(w.config.scheduler==='equal'?4:w.actors[id].capacity)-w.actors[id].busy);const urgent=id==='aspen'&&cap>0&&w.day>=w.aspenRoute.deadline;if(cost<=cap||(w.config.scheduler==='variable'&&urgent)){fn(w);if(w.returnLedger.length+w.evidence.length>before)w.actors[id].actions.push({day:w.day,cost,kind:'economic'})}}if(w.day===2&&w.actors.joel.knowledge.includes('news-screening'))w.actors.joel.location='old_hall';expirePerishables(w,Math.max(0,w.day-(w.perishClock??w.day-1)));w.perishClock=w.day;advanceLivingSystems(w);advanceRelationalHarbour(w);advanceProductionGame(w);settlePlayerDebts(w,w.day);rebuildOpportunities(w);resolvePlayerDay(w);return w}
export function assertHarbourInvariants(w){const units=Object.values(w.actors).flatMap(a=>a.inventory.map(x=>x.unitId));const duplicateUnits=units.filter((x,i)=>units.indexOf(x)!==i);const unexplained=w.externalFlows.filter(x=>!x.sector||!x.reason||!x.actorId||!(x.amount>0));const cashReservation=Object.keys(w.actors).every(id=>availableCash(w,id)>=0&&w.actors[id].cash>=0);const duplicateCollateral=w.claims.filter((c,i,a)=>c.status==='open'&&c.collateralAssetId&&a.findIndex(x=>x.status==='open'&&x.collateralAssetId===c.collateralAssetId)!==i);return{physicalConservation:!duplicateUnits.length,resourceReservation:cashReservation,settlementFloat:w.market.settlementFloat===0,externalFlowsExplained:!unexplained.length,claimsDistinct:!duplicateCollateral.length,duplicateUnits,unexplained,duplicateCollateral}}
export function spineDiagnostics(w){const tape=w.market.tape,bg=tape.filter(t=>w.actors[t.buyerId]?.background||w.actors[t.sellerId]?.background),player=tape.filter(t=>t.buyerId==='player'||t.sellerId==='player');return{day:w.day,fills:tape.length,backgroundFills:bg.length,playerFills:player.length,namedFills:tape.length-bg.length-player.length,uniqueGoods:new Set(tape.map(x=>x.item)).size,publicFacts:w.publicFacts.length,notices:w.evidence.filter(x=>x.type==='fact_noticed').length,informationChangedDecisions:w.stats.infoChangedDecisions,bar:{...w.bar.last,cycles:w.stats.barCycles,customers:w.stats.barCustomers,failures:w.stats.barFailures},aspen:{...w.aspenRoute,departures:w.stats.aspenDepartures,returns:w.stats.aspenReturns},actors:{wongJobs:w.stats.wongJobs,juanHarvests:w.stats.juanHarvests,yasminLoans:w.stats.yasminLoans,dimaServices:w.stats.dimaServices},externalIn:w.externalFlows.filter(x=>x.direction==='in').reduce((s,x)=>s+x.amount,0),externalOut:w.externalFlows.filter(x=>x.direction==='out').reduce((s,x)=>s+x.amount,0),opportunities:w.opportunities.length,invariants:assertHarbourInvariants(w)}}
export { GOODS, CLAIM_TYPES, SERVICE_TYPES, contentGraph, relationalDiagnostics, productionDiagnostics, sceneSnapshot };

export function finishPlayerIntervention(before,after,protectedActors=[]) {
 if(after.playerGame.lastBlock||after.attention.used<=before.attention.used)return after;
 const token=`${after.day}:${after.attention.used}`;
 if(after.relationshipEcology.beats?.some(b=>b.token===token))return after;
 const w=advanceHarbourBeat(after,token,protectedActors);
 // The four interventions cover the waking day; rollover owns the remaining night.
 const time=w.day+Math.min(.8,w.attention.used/Math.max(1,w.attention.budget)*.8);
 const elapsed=Math.max(0,time-(w.perishClock??w.day));
 expirePerishables(w,elapsed);w.perishClock=time;
 if(w.config.clearingAvailable!==false)clear(w);else expireOrders(w);
 settlePlayerDebts(w,time);
 rebuildOpportunities(w);
 return w;
}
