import {ACTION_COPY as COPY, actionIntent, friendlyBlock} from './presentationCopy.js';
import {reactionText} from './dialogueContent.js';
export {friendlyBlock};
export const ACTION_COPY=Object.fromEntries(Object.entries(COPY).map(([id,c])=>[id,[c.intent,c.terms||c.result]]));
export const TARGET_ACTIONS={
 aspen:['source_orgeat','source_invitation_fish','operate_inspection'],joel:['joel_hear_supper','joel_invitation','joel_supply_orgeat','joel_patronage','joel_help'],
 juan:['juan_plan','invest_nursery','finance_receivable','sell_toad'],yasmin:['auction_preview','auction_finance','repay_finance'],wong:['assemble_onewheel','sell_toad'],dima:['private_proxy'],
 crate:['lime_accept','lime_inspect','lime_represent','lime_refuse','lime_deliver'],cargo:['buy_part','source_orgeat','source_invitation_fish','operate_inspection'],
 bottle:['joel_supply_orgeat'],glass:['joel_patronage','joel_hear_supper','joel_help','intermediate_lead'],packing:['trade_bridge'],parcel:[],parts:['assemble_onewheel'],plants:['invest_nursery','juan_plan','invite_toad_circle'],paper:['finance_receivable'],bowl:['auction_preview','auction_inspect','auction_bid','auction_walk','speculate_lot'],photo:['auction_provenance','share_provenance'],envelope:['private_proxy','repay_finance'],table:['sonya_attend'],path:['cliff_commit'],orders:['restitution','fire_sale','misstate_public_listing'],toad:['collect_toad']
};
export function actionLine(a,w){if(a.id==='trade_bridge'&&w.production.tradeStock.length)return 'Would you buy the packing bundle?';return actionIntent(a)}
export function reaction(w,id){if(w.actors[id])return reactionText(w,id);const r=w.playerGame.routes;
 return {packing:w.production.tradeStock.length?'Your bundle of packing paper. Someone here may need it.':'A bundle left beside the counter. The price is 2 tins.',crate:w.playerGame.lime.inspected?'Twenty limes. Three bruised. A separate paper says 24.':'A tied crate. The paper says 24 limes.',cargo:'A manifest under a stone. Rope, bottles, cycle parts as the boats bring them.',bottle:'An almond syrup bottle behind the glasses.',glass:'A wet ring on the bar. Someone has just left.',parcel:'Paper, twine and a bundle waiting to be used.',parts:'A shared repair bench. It is busy on alternate days.',plants:'Pots in rows. Some leaves are greener than others.',paper:'A promise to pay, weighted down with a terracotta chip.',bowl:'A bowl on folded cloth. Look before offering money.',photo:'A photograph beside a label. Their marks can be compared.',envelope:'An envelope is pushed to the edge of the table.',table:r.sonya.stage==='invited'?`Your chair is waiting on day ${r.sonya.supperDay+1}. Bring the fresh catch.`:'Borrowed chairs around a kitchen table. This is someone else’s supper.',path:'Loose stones above the sea. The path is steep.',orders:'Leave a price with the clerk. As time passes, a matching buyer or seller can take it. Until then, the promised money or object is set aside.',toad:'Something moved under that leaf.'}[id]||'The harbour carries on.';
}
export function readableResult(before,after,a){if(after.playerGame.lastBlock)return friendlyBlock(after.playerGame.lastBlock);if(a.id==='trade_bridge')return after.production.tradeStock.length<before.production.tradeStock.length?`The bundle changes hands. You receive ${after.actors.player.cash-before.actors.player.cash} tins.`:'Two tins paid. The bundle is yours now.';if(a.id==='lime_represent')return 'She writes your words on the paper. The crate is still waiting for delivery.';if(a.id==='lime_deliver')return after.playerGame.lime.representation==='disclose'?'“Twenty, then.” She pays 6 tins and writes the shortage down.':'She pays 8. Later, the count does not match your words. She will remember.';if(a.id==='joel_invitation')return `“Day ${after.playerGame.routes.sonya.supperDay+1}. Bring the special fresh catch; it arrives the day before.”`;if(a.id==='buy_part')return `The ${a.payload.kind.toLowerCase()} is in your bag.`;if(a.id==='juan_plan')return COPY.juan_plan.terms;if(a.id==='auction_finance')return `Eight tins now. Repay nine on day ${after.claims.at(-1).dueDay+1}. ${after.actors.player.inventory.find(u=>u.pledgedTo)?.kind} is promised until you repay.`;const delta=after.actors.player.cash-before.actors.player.cash;return `${COPY[a.id]?.result||'The exchange is finished.'}${delta?` (${delta>0?'+':''}${delta} tins.)`:''}`}
