import { ECONOMIC_GOODS } from './economicContent.js';
const clone=x=>structuredClone(x); const CLASSES=['TRADE','OPERATE','INVEST','FINANCE','INTERMEDIATE','SPECULATE'];
const evt=(w,type,data={})=>{const e={id:`player-${++w.nextEvent}`,day:w.day,type,source:'local_action',location:w.playerGame.location,confidence:1,weight:2,...data};w.evidence.push(e);w.playerGame.notebook.push(e.id);return e};
const transfer=(w,from,to,amount)=>{if(w.actors[from].cash<amount)return false;w.actors[from].cash-=amount;w.actors[to].cash+=amount;return true};
const once=(w,id)=>!w.production.playerActions.some(x=>x.id===id&&x.day===w.day);
function record(w,id,returnClass,revenue,cost,counterparty,outcome='realised'){const profit=revenue-cost;w.production.playerActions.push({id,day:w.day,returnClass,revenue,cost,profit,counterparty,outcome});w.production.realised[returnClass]+=profit;evt(w,'specialist_return',{summary:`${id.replaceAll('_',' ')}: ${profit>=0?'+':''}${profit}🥫 after costs.`,returnClass,people:[counterparty],process:{execution:outcome==='realised'?.6:-.4,valuation:profit>=0?.4:-.3},context:{revenue,cost,profit,counterparty}});return profit}
export function initializeProductionGame(w){w.production={realised:Object.fromEntries(CLASSES.map(x=>[x,0])),playerActions:[],positions:[],claims:[],leads:[],tradeStock:[],equipmentLease:{available:true},marketStanding:{status:'OPEN',strikes:0,verificationLevel:0,depositRate:0,listingLimit:null,fines:0,restitution:0},misconduct:[],toads:[{id:'toad-1',location:'nursery',ownerId:null,custodianId:null,availableFrom:3,status:'hidden',reappearDay:null,appearances:1}],toadChat:null,sceneVisits:{},namedPlayerTransactions:[]};return w}
export function recordDiscoveredMisconduct(w,kind,evidenceId){const s=w.production.marketStanding;if(w.production.misconduct.some(x=>x.evidenceId===evidenceId))return;s.strikes++;s.verificationLevel=Math.min(3,s.strikes);s.depositRate=Math.min(.75,s.strikes*.2);s.listingLimit=s.strikes>=2?1:null;if(s.strikes>=3)s.status='SUSPENDED';else if(s.strikes>=2)s.status='RESTRICTED';const fine=s.strikes>=2?2*s.strikes:0;if(fine){const paid=Math.min(fine,w.actors.player.cash);w.actors.player.cash-=paid;s.fines+=paid}s.misconductLastDay=w.day;w.production.misconduct.push({day:w.day,kind,evidenceId,discovered:true});evt(w,s.strikes>=3?'confidence_run':'institutional_warning',{summary:s.strikes>=3?'Octopus suspended public listing access after repeated discovered misrepresentation.':'Octopus raised verification and deposit terms after discovered misrepresentation.',situation:s.strikes>=3?'THE_RUN':null,process:{marketStructure:-.5,commitments:-.5}})}
export function availableProductionActions(w){const l=w.playerGame.location,s=w.production.marketStanding,a=[];const add=(id,label,location,disabled=null)=>{if(l===location)a.push({id,label,disabled:!!disabled,reason:disabled})};add('trade_bridge',w.production.tradeStock.length?'Offer Wong’s packing bundle to Joel':'Buy Wong’s packing bundle','joels_bar',w.actors.player.cash<2&&!w.production.tradeStock.length?'Need 2🥫 available':null);add('operate_inspection','Inspect a named cargo lot for a fee','harbour_berth',!once(w,'operate_inspection')?'No second real lot is waiting today':null);add('invest_nursery','Fund a Juan cultivation batch','nursery',w.actors.player.cash<6?'Need 6🥫 available':null);add('finance_receivable','Factor Juan’s next output receivable','nursery',w.actors.player.cash<5?'Need 5🥫 available':null);add('intermediate_lead','Broker a fresh public lead to Joel','joels_bar',!w.publicFacts.some(f=>!w.production.leads.some(x=>x.factId===f.id))?'No fresh unsold lead':null);add('speculate_lot','Take a private position in a consigned lot','viewing_room',w.actors.player.cash<8?'Need 8🥫 available':null);add('private_proxy','Ask Dima for costly private execution','back_room',s.status!=='SUSPENDED'?'Public access is not suspended':w.actors.player.cash<3?'Need 3🥫 fee':null);add('misstate_public_listing','Publish a materially false condition statement','public_clearing',!once(w,'misstate_public_listing')?'A second discovered case cannot be manufactured today':!w.actors.player.inventory.length?'No owned physical unit to list':null);add('fire_sale','Liquidate locked stock under pressure','public_clearing',s.status!=='SUSPENDED'?'No confidence withdrawal is forcing a sale':!w.production.tradeStock.length?'No controlled stock to liquidate':null);add('share_provenance','Share your provenance comparison with a rival','viewing_room',!w.playerGame.routes.yasmin.provenance?'No provenance comparison to disclose':null);add('restitution','File restitution and certification','public_clearing',s.strikes<1?'No discovered case to repair':w.actors.player.cash<4?'Need 4🥫':null);return a}
export function performProductionAction(current,id){const w=clone(current),p=w.actors.player;if(!once(w,id))return w;
 if(id==='trade_bridge'&&w.playerGame.location==='joels_bar'){if(!w.production.tradeStock.length&&transfer(w,'player','wong',2)){w.production.tradeStock.push({kind:'packing_bundle',cost:2,boughtDay:w.day});evt(w,'price_gap_seen',{summary:'Wong’s cheap packing bundle answers a recurring Bar need.',situation:'THE_GAP'});}else if(w.production.tradeStock.length){const stock=w.production.tradeStock.shift(),buyer=w.day%4===0?'wong':'joel',gross=buyer==='joel'?4:1;if(w.actors[buyer].cash>=gross){w.actors[buyer].cash-=gross;p.cash+=gross;record(w,id,'TRADE',gross,stock.cost,buyer,gross>stock.cost?'realised':'loss');evt(w,'market_fill',{summary:`Closed the packing spread with ${buyer}.`,situation:gross>stock.cost?'THE_GAP':'THIN_BOOK'});}}}
 if(id==='operate_inspection'&&w.playerGame.location==='harbour_berth'){w.actors.aspen.cash-=4;p.cash+=3;record(w,id,'OPERATE',4,1,'aspen');}
 if(id==='invest_nursery'&&w.playerGame.location==='nursery'&&transfer(w,'player','juan',6)){w.production.positions.push({id:`crop-stake-${w.day}`,class:'INVEST',opened:w.day,due:w.day+5,cost:6,status:'open',counterparty:'juan'});record(w,id,'INVEST',0,6,'juan','locked');}
 if(id==='finance_receivable'&&w.playerGame.location==='nursery'&&transfer(w,'player','juan',5)){const c={id:`factored-${w.day}`,issuerId:'juan',holderId:'player',face:7,cost:5,dueDay:w.day+4,status:'open'};w.claims.push(c);w.production.claims.push(c.id);record(w,id,'FINANCE',0,5,'juan','locked');}
 if(id==='intermediate_lead'&&w.playerGame.location==='joels_bar'){const fact=w.publicFacts.find(f=>!w.production.leads.some(x=>x.factId===f.id));if(fact&&w.actors.joel.cash>=3){w.actors.joel.cash-=3;p.cash+=3;w.production.leads.push({factId:fact.id,buyer:'joel',day:w.day,exclusiveUntil:w.day+2});record(w,id,'INTERMEDIATE',3,0,'joel');evt(w,'private_lead_sold',{summary:`Sold ${fact.headline} as a timely lead before it went stale.`,situation:'THE_PRIVATE_LEAD'});}}
 if(id==='speculate_lot'&&w.playerGame.location==='viewing_room'&&transfer(w,'player','yasmin',8)){w.production.positions.push({id:`consignment-${w.day}`,class:'SPECULATE',opened:w.day,due:w.day+3,cost:8,status:'open',counterparty:'yasmin'});record(w,id,'SPECULATE',0,8,'yasmin','illiquid');}
 if(id==='private_proxy'&&w.playerGame.location==='back_room'&&w.production.marketStanding.status==='SUSPENDED'&&transfer(w,'player','dima',3)){const gross=5+(w.seed+w.day)%4;w.actors.dima.cash-=gross;p.cash+=gross;record(w,id,'INTERMEDIATE',gross,3,'dima',gross>3?'realised':'loss');evt(w,'private_venue_used',{summary:'Used Dima’s costly private settlement while public listing access was suspended.',situation:'THE_WRONG_VENUE'});}
 if(id==='misstate_public_listing'&&w.playerGame.location==='public_clearing'&&w.actors.player.inventory.length&&once(w,id)){const item=w.actors.player.inventory[0];const evidence=evt(w,'public_misstatement_discovered',{summary:`Octopus verification found the listed condition of ${item.kind} materially false.`,goods:[item.kind],situation:'THE_RUN'});recordDiscoveredMisconduct(w,'public_listing',evidence.id);w.production.playerActions.push({id,day:w.day,returnClass:'TRADE',revenue:0,cost:0,profit:0,counterparty:'octopus_clearing',outcome:'discovered'});}
 if(id==='fire_sale'&&w.playerGame.location==='public_clearing'&&w.production.marketStanding.status==='SUSPENDED'&&w.production.tradeStock.length){const stock=w.production.tradeStock.shift();w.actors.households.cash-=1;p.cash+=1;record(w,id,'TRADE',1,stock.cost,'households','forced_loss');evt(w,'liquidity_sale',{summary:'Sold controlled stock below cost after public confidence disappeared.',situation:'THE_RUN'});evt(w,'market_fill',{summary:'The forced sale found only thin background demand.',situation:'THIN_BOOK'});}
 if(id==='share_provenance'&&w.playerGame.location==='viewing_room'&&w.playerGame.routes.yasmin.provenance){evt(w,'provenance_shared',{summary:'Shared the documentary edge with a competing bidder.',people:['yasmin'],situation:'HAMMER_NIGHT'});}
 if(id==='restitution'&&w.playerGame.location==='public_clearing'&&w.production.marketStanding.strikes&&p.cash>=4){p.cash-=4;const s=w.production.marketStanding;s.restitution+=4;s.strikes--;s.status=s.strikes>=2?'RESTRICTED':'OPEN';s.listingLimit=s.strikes>=2?1:null;s.depositRate=s.strikes*.2;record(w,id,'OPERATE',0,4,'octopus_clearing','reputation_repair');}
 return w}
export function advanceProductionGame(w){for(const t of w.production.toads)if(['sold','shared'].includes(t.status)&&t.reappearDay<=w.day&&t.appearances<3){t.status='hidden';t.ownerId=null;t.custodianId=null;t.location=t.appearances%2?'harbour_berth':'nursery';t.availableFrom=w.day;t.appearances++}for(const position of w.production.positions.filter(x=>x.status==='open'&&x.due<=w.day)){const good=(w.seed+position.opened)%4!==0,gross=position.class==='INVEST'?(good?9:3):(good?12:5),payer=position.class==='INVEST'?w.actors.households:w.actors[position.counterparty];const localPaid=Math.min(gross,payer.cash);payer.cash-=localPaid;const externalPaid=gross-localPaid;if(externalPaid)w.externalFlows.push({day:w.day,direction:'in',sector:'produce_buyers',actorId:'player',reason:'contracted_crop_or_consignment_buyer',amount:externalPaid,returnClass:position.class});const paid=localPaid+externalPaid;w.actors.player.cash+=paid;position.status=good?'settled':'loss';record(w,`${position.id}_exit`,position.class,paid,0,position.counterparty,position.status)}for(const claim of w.claims.filter(x=>w.production.claims.includes(x.id)&&x.status==='open'&&x.dueDay<=w.day)){let paid=Math.min(claim.face,Math.max(0,w.actors.juan.cash-3));w.actors.juan.cash-=paid;const outputBuyer=w.actors.crews,shortfall=Math.min(claim.face-paid,Math.max(0,outputBuyer.cash-5));outputBuyer.cash-=shortfall;paid+=shortfall;const external=Math.max(0,claim.face-paid);if(external)w.externalFlows.push({day:w.day,direction:'in',sector:'contract_output_buyers',actorId:'player',reason:'juan_factored_output_sale',amount:external,returnClass:'FINANCE'});paid+=external;w.actors.player.cash+=paid;claim.status=paid===claim.face?'settled':'default';record(w,`${claim.id}_collection`,'FINANCE',paid,0,'juan',claim.status);if(claim.status==='default')evt(w,'claim_default',{summary:'The factored output claim defaulted and required a workout.',situation:'JUAN_PAPER'})}return w}
export function collectHiddenToad(current,toadId){const w=clone(current),t=w.production.toads.find(x=>x.id===toadId);if(!t||t.status!=='hidden'||w.day<t.availableFrom||t.location!==w.playerGame.location)return w;t.status='held';t.ownerId='player';t.custodianId='player';evt(w,'toad_found',{summary:'You noticed a toad where the scene almost hid it. Collecting it used no additional attention.',goods:[t.id],weight:1});return w}
export function useToad(current,mode,target='juan'){const w=clone(current),t=w.production.toads.find(x=>x.ownerId==='player'&&x.status==='held');if(!t)return w;if(mode==='sell'&&['juan','aspen','wong'].includes(target)&&w.actors[target].cash>=2){w.actors[target].cash-=2;w.actors.player.cash+=2;t.ownerId=target;t.custodianId=target;t.status='sold';t.reappearDay=w.day+18;record(w,'toad_sale','TRADE',2,0,target)}if(mode==='invite'){const attending=['juan','aspen','wong','joel'].filter(id=>w.actors[id].location!=='away'&&!w.actors[id].removed);t.status='shared';t.ownerId=null;t.custodianId='juan';t.reappearDay=w.day+18;w.production.toadChat={createdDay:w.day,members:['player',...attending],messages:['🐸🌒❓','juan: 🔁≠答案','aspen: ⏱️➡️码头','wong: 🫙先洗。','joel: …你们点单吗？']};evt(w,'toad_circle_invited',{summary:`Invited the circle; ${attending.join(', ')} could actually attend.`,people:attending})}return w}
export function productionDiagnostics(w){return{realised:w.production.realised,actions:w.production.playerActions,standing:w.production.marketStanding,toads:w.production.toads,toadChat:w.production.toadChat,namedPlayerTransactions:w.production.playerActions.length}}
