const NAMES=['aspen','joel','yasmin','wong','juan','dima'];
const CHANNELS=['SOCIAL','TRADE','SERVICE','FINANCE','INFORMATION','OBLIGATION','CONFLICT'];
const pair=(a,b)=>[a,b].sort().join(':');
const relation=()=>({familiarity:0,affection:0,businessUsefulness:0,paymentReliability:3,deliveryReliability:3,representationReliability:3,creditExposure:0,obligation:0,friction:0,privateAccess:0});
const DRINKING={aspen:{visit:2,ceiling:5,impairmentAversion:5,social:3,tab:0,round:0,leave:5,nextDay:5},joel:{visit:5,ceiling:4,impairmentAversion:3,social:5,tab:4,round:3,leave:2,nextDay:2},yasmin:{visit:2,ceiling:8,impairmentAversion:5,social:4,tab:0,round:2,leave:4,nextDay:4},wong:{visit:2,ceiling:3,impairmentAversion:4,social:2,tab:1,round:1,leave:5,nextDay:4},juan:{visit:4,ceiling:5,impairmentAversion:1,social:4,tab:5,round:2,leave:1,nextDay:2},dima:{visit:3,ceiling:8,impairmentAversion:5,social:3,tab:0,round:4,leave:4,nextDay:4}};
const ROUTES={short:{duration:2,cost:6,revenue:11,cargo:['Hardtack Tin','Packing Paper'],risk:1},medium:{duration:3,cost:10,revenue:18,cargo:['Lime','Rum','Presta Inner Tube'],risk:3},outer:{duration:5,cost:17,revenue:31,cargo:['Brass Compass','Gelatin Silver Print, 20 × 25 cm'],risk:6}};
const CANDIDATES=[
 ['aspen','joel','TRADE','joels_bar','bar_import_bundle',2,4,3],['aspen','yasmin','SERVICE','viewing_room','provenance_delivery',3,6,5],['aspen','wong','SERVICE','parcel_counter','ordinary_gift_custody',2,3,4],['aspen','juan','INFORMATION','nursery','route_measurements',0,4,5],['aspen','dima','SERVICE','back_room','discreet_timed_delivery',3,5,7],
 ['joel','yasmin','SOCIAL','joels_bar','patron_hosting',2,3,6],['joel','wong','TRADE','joels_bar','salvage_glass',1,3,4],['joel','juan','OBLIGATION','joels_bar','bounded_bar_tab',0,5,3],['joel','dima','SERVICE','joels_bar','closing_settlement',2,4,5],
 ['yasmin','wong','INFORMATION','parcel_counter','odd_object_provenance',1,4,7],['yasmin','juan','FINANCE','nursery','productive_claim_review',5,6,6],['yasmin','dima','SERVICE','back_room','claim_formalisation',2,5,8],
 ['wong','juan','TRADE','nursery','weird_small_sourcing',1,4,5],['wong','dima','SERVICE','parcel_counter','custody_guarantee',2,5,6],['juan','dima','FINANCE','back_room','claim_workout',2,6,7],
 ['wong','aspen','OBLIGATION','parcel_counter','gift_handoff',0,5,8],['juan','joel','SOCIAL','joels_bar','friendship_visit',3,4,4],['dima','yasmin','INFORMATION','viewing_room','disputed_claim_notice',0,4,9],['dima','joel','SOCIAL','joels_bar','business_round',4,3,7],['wong','yasmin','TRADE','viewing_room','street_source_offer',2,4,9],['juan','aspen','SOCIAL','nursery','toad_protocol_check',0,3,9],['dima','wong','CONFLICT','parcel_counter','guarantee_fee_counter',0,4,10]
].map(([initiator,target,channel,location,purpose,cash,utility,cadence],i)=>({id:`rel-${i}`,initiator,target,targets:[target],channel,location,purpose,cashRequirement:cash,resourceRequirement:channel==='TRADE'?'physical_stock':null,opportunityCost:1,knowledgePrerequisite:null,relationshipPrerequisite:0,privacy:location==='back_room',utility,risk:channel==='FINANCE'?3:1,cadence,deadlineOffset:2,responses:['ACCEPT','REFUSE','COUNTER','DELAY','REDIRECT'],resultingStateChanges:['cash','knowledge','relationship','obligation','location','agenda']}));
function emit(w,type,data){const row={id:`ev${++w.nextEvent}`,day:w.day,type,...data};w.evidence.push(row);w.activityLog?.push(row);return row}
function active(w,id){return w.actors[id]&&!w.actors[id].removed&&w.actors[id].capacity>0}
function rel(w,a,b){return w.relationshipEcology.relations[pair(a,b)]}
function record(w,c,response,value=0,info=0,obligation=0,reason=''){const row={id:`ri${++w.relationshipEcology.nextId}`,day:w.day,initiator:c.initiator,target:c.target,targets:c.targets,location:c.location,channel:c.channel,purpose:c.purpose,response,accepted:response==='ACCEPT',refused:['REFUSE','COUNTER','DELAY','REDIRECT'].includes(response),valueTransferred:value,informationTransferred:info,obligationsCreated:obligation,coPresence:response==='ACCEPT',reason};w.relationshipEcology.interactions.push(row);if(value)w.privateTransactions.push({day:w.day,kind:'named_relational_transfer',channel:c.channel,from:c.initiator,to:c.target,amount:value,purpose:c.purpose});w.relationshipEcology.traces.unshift({...row,summary:traceText(c,response)});w.relationshipEcology.traces=w.relationshipEcology.traces.slice(0,24);emit(w,'relational_interaction',row);return row}
function traceText(c,response){const verbs={ACCEPT:'agreed',REFUSE:'refused',COUNTER:'countered',DELAY:'asked for time on',REDIRECT:'redirected'};return `${c.initiator} ${verbs[response].toLowerCase()} ${c.target}’s ${c.purpose.replaceAll('_',' ')}.`}
function targetResponse(w,c){const initiator=w.actors[c.initiator],reserve=c.initiator==='aspen'?10:c.initiator==='joel'?8:3;if(c.cashRequirement&&initiator.cash-c.cashRequirement<reserve)return 'COUNTER';const target=w.actors[c.target],r=rel(w,c.initiator,c.target);if(!active(w,c.target))return 'REDIRECT';if(target.busy>=target.capacity-1)return 'DELAY';if(c.cashRequirement&&target.cash<c.cashRequirement)return 'COUNTER';if(c.privacy&&r.privateAccess<1&&c.channel!=='SERVICE')return 'REFUSE';if(r.friction>3)return 'REFUSE';return 'ACCEPT'}
function transferInfo(w,c){const source=w.actors[c.initiator],target=w.actors[c.target],fact=source.knowledge.find(id=>!target.knowledge.includes(id));if(!fact)return 0;target.knowledge.push(fact);w.relationshipEcology.information.push({day:w.day,factId:fact,from:c.initiator,to:c.target,source:'conversation',freshness:'current'});return 1}
function execute(w,c){const response=targetResponse(w,c),r=rel(w,c.initiator,c.target);r.familiarity+=.2;if(response!=='ACCEPT'){r.friction+=response==='REFUSE'?.25:.05;return record(w,c,response,0,0,0,response==='DELAY'?'target capacity committed':'terms or access did not clear')}
 const a=w.actors[c.initiator],b=w.actors[c.target];a.location=c.location;b.location=c.location;a.busy=Math.min(a.capacity,a.busy+1);b.busy=Math.min(b.capacity,b.busy+1);let value=0,obligation=0,info=0;
 if(c.cashRequirement&&a.cash>=c.cashRequirement){a.cash-=c.cashRequirement;b.cash+=c.cashRequirement;value=c.cashRequirement}
 if(c.channel==='INFORMATION'||c.channel==='SOCIAL')info=transferInfo(w,c);
 if(c.channel==='OBLIGATION'){obligation=1;const o={id:`npc-ob-${w.relationshipEcology.nextId}`,debtorId:c.initiator,holderId:c.target,purpose:c.purpose,createdDay:w.day,dueDay:w.day+c.deadlineOffset,status:'open'};w.relationshipEcology.obligations.push(o);r.obligation++}
 if(c.purpose==='bounded_bar_tab'){const existing=w.claimRights.tabs.filter(x=>x.issuerId==='juan'&&x.state==='open').reduce((n,x)=>n+x.face,0);if(existing>=6)return record(w,c,'REFUSE',0,0,0,'Joel’s tab boundary is already reached');w.claimRights.tabs.push({id:`juan-tab-${w.day}`,issuerId:'juan',holderId:'joel',face:2,maturity:w.day+5,state:'open'});r.creditExposure+=2;obligation++}
 if(c.purpose==='ordinary_gift_custody')createGift(w,false);
 if(c.purpose==='discreet_timed_delivery')createGift(w,true);
 r.businessUsefulness+=['TRADE','SERVICE','FINANCE'].includes(c.channel)?.3:.05;r.affection+=c.channel==='SOCIAL'?.2:0;r.privateAccess+=c.privacy?.15:0;return record(w,c,'ACCEPT',value,info,obligation)}
function createGift(w,privateRoute){if(w.relationshipEcology.gifts.some(x=>x.status==='in_transit')||w.day-Math.max(0,...w.relationshipEcology.gifts.map(x=>x.createdDay||0))<12)return;const ordinary=active(w,'wong')&&!privateRoute;const specialist=privateRoute&&active(w,'dima');w.relationshipEcology.gifts.push({id:`wrapped-gift-${w.day}`,ownerId:'aspen',recipientId:'offscreen_support',custodianId:ordinary?'wong':null,settlementAgentId:specialist?'dima':null,contents:'wrapped personal gift',identityResolved:false,createdDay:w.day,dueDay:w.day+3,status:'in_transit',privacy:privateRoute});}
function chooseAspenRoute(w){if(!active(w,'aspen')||w.aspenRoute.status!=='preparing')return;const gift=w.relationshipEcology.gifts.find(x=>x.status==='in_transit'),weatherPenalty=w.weather==='storm'?5:0;const obligations=w.relationshipEcology.obligations.filter(x=>x.debtorId==='aspen'&&x.status==='open').length;const scored=Object.entries(ROUTES).map(([id,r])=>({id,...r,score:r.revenue-r.cost-r.risk-weatherPenalty*(id!=='short')-(obligations+Boolean(gift))*(r.duration-2)})).filter(r=>w.actors.aspen.cash>=r.cost).sort((a,b)=>b.score-a.score||a.duration-b.duration);const chosen=scored[0];if(!chosen)return;w.aspenRoute.selectedRoute=chosen.id;w.aspenRoute.travelTime=chosen.duration;w.aspenRoute.routeOptions=scored.map(x=>({id:x.id,score:x.score,cost:x.cost,revenue:x.revenue,duration:x.duration}));w.aspenRoute.cargoPlan=[...chosen.cargo];if(!w.relationshipEcology.routeDecisions.some(x=>x.day===w.day))w.relationshipEcology.routeDecisions.push({day:w.day,route:chosen.id,score:chosen.score,weather:w.weather,obligations,gift:Boolean(gift),cargo:[...chosen.cargo]});if(gift&&w.aspenRoute.cargoPlan.length<4)w.aspenRoute.cargoPlan.push(gift.id)}
function barAttendance(w){if(!active(w,'joel'))return;const attendees=['joel'];for(const id of NAMES.filter(x=>x!=='joel'&&active(w,x))){const p=DRINKING[id],actor=w.actors[id],urgent=id==='aspen'&&(w.aspenRoute.status==='away'||w.day>=w.aspenRoute.deadline-1),auction=id==='yasmin'&&w.playerGame?.routes.yasmin.auctionDay-w.day<=1,score=p.visit+p.social-(urgent?6:0)-(auction?3:0)-(actor.busy>=actor.capacity-1?4:0);if(score>=5&&(w.day+NAMES.indexOf(id))%3===0)attendees.push(id)}
 if(attendees.length<2)return;for(const id of attendees)w.actors[id].location='joels_bar';const served=[];for(const id of attendees.filter(x=>x!=='joel')){const a=w.actors[id],p=DRINKING[id],price=3;if(a.cash>=price&&price<=p.ceiling){a.cash-=price;w.actors.joel.cash+=price;w.privateTransactions.push({day:w.day,kind:'named_bar_service',from:id,to:'joel',amount:price});served.push(id)}else if(id==='juan'&&w.claimRights.tabs.filter(x=>x.issuerId==='juan'&&x.state==='open').reduce((n,x)=>n+x.face,0)<6){w.claimRights.tabs.push({id:`bar-social-tab-${w.day}`,issuerId:'juan',holderId:'joel',face:price,maturity:w.day+4,state:'open'});served.push(id)}if(p.nextDay>=4&&served.includes(id))w.relationshipEcology.capacityEffects.push({actorId:id,day:w.day+1,amount:1,reason:'late social obligation'})}
 w.relationshipEcology.barEvenings.push({day:w.day,attendees,served,earlyExit:attendees.filter(id=>id==='aspen'||id==='wong')});emit(w,'named_bar_evening',{attendees,served})}
function toadAftermath(w){const occurrence=w.toadCircle?.occurrences.find(x=>x.day===w.day);if(!occurrence)return;const unavailable=w.toadCircle.members.filter(id=>!occurrence.attending.includes(id));for(const id of occurrence.attending){w.actors[id].busy=Math.min(w.actors[id].capacity,w.actors[id].busy+1);if(id==='aspen'&&w.aspenRoute.deadline-w.day<=1)w.relationshipEcology.traces.unshift({day:w.day,location:'juan_nursery',summary:'Aspen left the circle early to protect a departure promise.'})}w.relationshipEcology.sharedEvents.push({type:'toad_circle',day:w.day,attending:occurrence.attending,unavailable,consequence:'bounded recovery time; no commodity or score'})}
function yasminAgenda(w){if(!active(w,'yasmin'))return;const auction=w.playerGame?.routes.yasmin;if(auction&&w.day>=auction.previewOpens&&w.day<=auction.previewCloses&&w.day!==4){w.actors.yasmin.location='viewing_room';w.actors.yasmin.actions.push({day:w.day,kind:w.day===auction.previewCloses?'auction preparation':'appraisal and provenance work'})}else if(w.day%7===0){w.actors.yasmin.location='private';w.actors.yasmin.actions.push({day:w.day,kind:'family capital call'})}else if(w.day%4===0){w.actors.yasmin.location='joels_bar';w.actors.yasmin.actions.push({day:w.day,kind:'social maintenance'})}}
function auctionAttendance(w){const auctionDay=w.playerGame?.routes.yasmin.auctionDay;if(w.day!==auctionDay)return;const roles={yasmin:'HOST'};if(active(w,'dima')&&w.claims.some(c=>c.status==='open'))roles.dima='CLIENT REPRESENTATIVE';if(active(w,'wong')&&w.actors.wong.cash>=8)roles.wong='SELLER/SOURCER';if(active(w,'joel')&&w.actors.joel.cash>=12&&w.actors.joel.busy<4)roles.joel='OBSERVER';if(active(w,'juan')&&w.livingAssets.some(x=>x.health<.7))roles.juan='BIDDER';if(active(w,'aspen')&&w.aspenRoute.status!=='away'&&w.aspenRoute.deadline>w.day+1)roles.aspen='OBSERVER';for(const id of Object.keys(roles))w.actors[id].location='viewing_room';w.relationshipEcology.auctions.push({day:w.day,roles,absent:NAMES.filter(id=>!roles[id])});emit(w,'auction_attendance',{roles})}
function settleRelationalObligations(w){for(const o of w.relationshipEcology.obligations.filter(x=>x.status==='open'&&x.dueDay<=w.day)){const debtor=w.actors[o.debtorId];o.status=active(w,o.debtorId)&&debtor.busy<debtor.capacity?'fulfilled':'breached';const r=rel(w,o.debtorId,o.holderId);r.obligation=Math.max(0,r.obligation-1);if(o.status==='fulfilled')r.deliveryReliability+=.1;else r.friction+=.4;emit(w,'relational_obligation_resolved',{obligationId:o.id,status:o.status,debtorId:o.debtorId,holderId:o.holderId})}for(const tab of w.claimRights.tabs.filter(x=>x.state==='open'&&x.maturity<=w.day)){const juan=w.actors.juan;if(active(w,'juan')&&juan.cash-tab.face>=4){juan.cash-=tab.face;w.actors.joel.cash+=tab.face;tab.state='settled';w.privateTransactions.push({day:w.day,kind:'bar_tab_payment',from:'juan',to:'joel',amount:tab.face})}else{tab.state='default';rel(w,'joel','juan').friction+=.5;emit(w,'bar_tab_boundary',{tabId:tab.id,state:'default'})}}}
function settleGifts(w){for(const g of w.relationshipEcology.gifts.filter(x=>x.status==='in_transit'&&x.dueDay<=w.day)){if((g.custodianId&&active(w,g.custodianId))||(g.settlementAgentId&&active(w,g.settlementAgentId))){g.status='delivered';rel(w,'aspen',g.custodianId||g.settlementAgentId).deliveryReliability+=.2;w.relationshipEcology.traces.unshift({day:w.day,location:g.custodianId?'parcel_counter':'back_room',summary:'A wrapped gift left custody on time. The recipient stayed outside the frame.'})}else{g.status='missed';w.relationshipEcology.traces.unshift({day:w.day,location:'harbour_berth',summary:'A two-seat reservation passed with one place still empty.'})}}}
export function initializeRelationalHarbour(w){w.relationshipEcology={nextId:0,relations:{},candidates:CANDIDATES,interactions:[],traces:[],obligations:[],information:[],gifts:[],barEvenings:[],sharedEvents:[],auctions:[],capacityEffects:[],routeDecisions:[],drinkingProfiles:DRINKING,routeGraph:ROUTES};for(let i=0;i<NAMES.length;i++)for(let j=i+1;j<NAMES.length;j++)w.relationshipEcology.relations[pair(NAMES[i],NAMES[j])]=relation();return w}
export function prepareRelationalDay(w){for(const effect of w.relationshipEcology.capacityEffects.filter(x=>x.day===w.day))if(active(w,effect.actorId))w.actors[effect.actorId].busy+=effect.amount;chooseAspenRoute(w);return w}
export function advanceRelationalHarbour(w){const candidates=CANDIDATES.filter(c=>active(w,c.initiator)&&active(w,c.target)&&(w.day+c.utility+(w.seed%5))%c.cadence===0).sort((a,b)=>b.utility-a.utility||a.id.localeCompare(b.id));const used=new Set();for(const c of candidates){if(used.has(c.initiator)||w.actors[c.initiator].busy>=w.actors[c.initiator].capacity)continue;execute(w,c);used.add(c.initiator)}barAttendance(w);yasminAgenda(w);toadAftermath(w);auctionAttendance(w);settleRelationalObligations(w);settleGifts(w);return w}
export function relationalDiagnostics(w){const matrix={};for(const a of NAMES)for(const b of NAMES)if(a!==b){const rows=w.relationshipEcology.interactions.filter(x=>x.initiator===a&&x.target===b);matrix[`${a}->${b}`]={initiated:rows.length,accepted:rows.filter(x=>x.accepted).length,refusedOrCountered:rows.filter(x=>x.refused).length,valueTransferred:rows.reduce((n,x)=>n+x.valueTransferred,0),informationTransferred:rows.reduce((n,x)=>n+x.informationTransferred,0),obligationsCreated:rows.reduce((n,x)=>n+x.obligationsCreated,0),coPresence:rows.filter(x=>x.coPresence).length,channels:[...new Set(rows.map(x=>x.channel))]}}const undirectedPairs=new Set(w.relationshipEcology.candidates.map(c=>pair(c.initiator,c.target)));const counts=Object.values(matrix).map(x=>x.initiated).filter(Boolean),total=counts.reduce((a,b)=>a+b,0),entropy=total? -counts.reduce((n,x)=>{const p=x/total;return n+p*Math.log2(p)},0):0;return{day:w.day,matrix,executablePairCount:undirectedPairs.size,totalInteractions:w.relationshipEcology.interactions.length,accepted:w.relationshipEcology.interactions.filter(x=>x.accepted).length,refusedOrCountered:w.relationshipEcology.interactions.filter(x=>x.refused).length,entropy,barEvenings:w.relationshipEcology.barEvenings,gifts:w.relationshipEcology.gifts,auctions:w.relationshipEcology.auctions,sharedEvents:w.relationshipEcology.sharedEvents,routeChoices:w.relationshipEcology.routeDecisions}}
export function sceneSnapshot(w,location){const people=NAMES.filter(id=>active(w,id)&&w.actors[id].location===location),base={joels_bar:['bar','tonight menu','open tab'],parcel_counter:['parcel','packing paper','handling bench','handoff door'],nursery:['living plants','tools','onewheel parts',...(w.toadCircle?.occurrences.some(x=>x.day===w.day)?['toad container']:[])],viewing_room:['auction lot','labels','provenance documents'],harbour_berth:['cargo manifest','mooring line','wrapped parcel'],back_room:['claim papers','settlement envelope'],workbench:['newspaper','phone','notebook','ledger'],sonyas_kitchen:['table','borrowed chairs'],cliff_path:['cliff path']}[location]||[];return{location,people,objects:base,traces:w.relationshipEcology.traces.filter(x=>x.location===location).slice(0,4),actions:[]}}
export { NAMES as RELATIONAL_ACTORS, CHANNELS as RELATIONAL_CHANNELS };
